name: CI

on:
  push:
    branches:
      - '*'

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true

    steps:
      # Grab The Source Code
      - name: Checkout
        uses: actions/checkout@v2

      # Build the Project
      - name: Build Source
        run: dotnet build --configuration Release

      # Run the Tests
      - name: Run Tests
        run: dotnet test --configuration Release

  build-windows:
    runs-on: windows-latest
    env:
      DOTNET_NOLOGO: true

    steps:
      # Grab The Source Code
      - name: Checkout
        uses: actions/checkout@v2

      # Build the Project
      - name: Build Source
        run: dotnet build --configuration Release

      # Run the Tests
      - name: Run Tests
        run: dotnet test --configuration Release
